# Generated by Django 3.0.8 on 2020-08-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('O', 'Outer'), ('T', 'Top'), ('S', 'Skirt'), ('P', 'Pants')], max_length=2)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
